#!/bin/sh

bspc config border_width        2
bspc config window_gap          15

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true

#bspc config presel_feedback_color "#$(getXresColor color1)"
#bspc config active_border_color "#$(getXresColor color1)"
bspc config focused_border_color "#959DCB"
bspc config normal_border_color "#292D3E"

#set up the desired amount of workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Chromium desktop='^2'

#Run compton as a composite manager
if [[ $(pgrep "^compton") ]]; then
	kill $(pgrep "^compton");
fi
compton -cfb &

#Launch Polybar
if [[ $(pgrep "^polybar") ]]; then
	pkill polybar;
fi
polybar manasv &
